### ISSUE TITLE
out of memoy - Try to recover

### ISSUE THREAD

**Issue by victordalosto** [victordalosto/sist-down#6]
Fazer uma tentativa de recuperar o progresso caso o usuário tenha recebido o problema de out of memory.

**Comment by remayke** [comment]
Como a solução desse problema é um trabalho um tanto complexo, e dado a falta de para focar nessa issue, a melhor solução é deixar a exception ser lançada, e o próprio usuario precisa liberar memoria no computador para continuar os trabalhos.
